using System;
using System.Collections.Generic;
using System.Text;

namespace NetBlox.Common
{
	/// <summary>
	/// Quite literally represents a real-world political states (i.e. French Republic, United Kingdom, Russian Federation, etc)
	/// </summary>
	public class PoliticalState(string sn, string cc)
	{
		public string Name = sn;
		public string CountryCode = cc;
		public string FlagUrl = "";

		public override bool Equals(object? obj)
		{
			if (obj is PoliticalState ps)
				return ps.CountryCode == CountryCode;
			return false;
		}
		public override int GetHashCode() => CountryCode.GetHashCode();
		public static bool operator !=(PoliticalState a, PoliticalState b) => a.CountryCode != b.CountryCode;
		public static bool operator ==(PoliticalState a, PoliticalState b) => a.CountryCode == b.CountryCode;

		// tbh chatgpt came up with this list and i bet there's something mixed up
		public readonly static PoliticalState[] UNMemberCountries =
		{
			new ("Pseudoland (unknown country)", "PS"),

			new ("Afghanistan", "AF"),
			new ("Albania", "AL"),
			new ("Algeria", "DZ"),
			new ("Andorra", "AD"),
			new ("Angola", "AO"),
			new ("Antigua and Barbuda", "AG"),
			new ("Argentina", "AR"),
			new ("Armenia", "AM"),
			new ("Australia", "AU"),
			new ("Austria", "AT"),
			new ("Azerbaijan", "AZ"),
			new ("Bahamas", "BS"),
			new ("Bahrain", "BH"),
			new ("Bangladesh", "BD"),
			new ("Barbados", "BB"),
			new ("Belarus", "BY"),
			new ("Belgium", "BE"),
			new ("Belize", "BZ"),
			new ("Benin", "BJ"),
			new ("Bhutan", "BT"),
			new ("Bolivia", "BO"),
			new ("Bosnia and Herzegovina", "BA"),
			new ("Botswana", "BW"),
			new ("Brazil", "BR"),
			new ("Brunei Darussalam", "BN"),
			new ("Bulgaria", "BG"),
			new ("Burkina Faso", "BF"),
			new ("Burundi", "BI"),
			new ("Cabo Verde", "CV"),
			new ("Cambodia", "KH"),
			new ("Cameroon", "CM"),
			new ("Canada", "CA"),
			new ("Central African Republic", "CF"),
			new ("Chad", "TD"),
			new ("Chile", "CL"),
			new ("China", "CN"),
			new ("Colombia", "CO"),
			new ("Comoros", "KM"),
			new ("Congo (Congo-Brazzaville)", "CG"),
			new ("Costa Rica", "CR"),
			new ("Croatia", "HR"),
			new ("Cuba", "CU"),
			new ("Cyprus", "CY"),
			new ("Czechia (Czech Republic)", "CZ"),
			new ("Democratic Republic of the Congo", "CD"),
			new ("Denmark", "DK"),
			new ("Djibouti", "DJ"),
			new ("Dominica", "DM"),
			new ("Dominican Republic", "DO"),
			new ("Ecuador", "EC"),
			new ("Egypt", "EG"),
			new ("El Salvador", "SV"),
			new ("Equatorial Guinea", "GQ"),
			new ("Eritrea", "ER"),
			new ("Estonia", "EE"),
			new ("Eswatini (fmr. 'Swaziland')", "SZ"),
			new ("Ethiopia", "ET"),
			new ("Fiji", "FJ"),
			new ("Finland", "FI"),
			new ("France", "FR"),
			new ("Gabon", "GA"),
			new ("Gambia", "GM"),
			new ("Georgia", "GE"),
			new ("Germany", "DE"),
			new ("Ghana", "GH"),
			new ("Greece", "GR"),
			new ("Grenada", "GD"),
			new ("Guatemala", "GT"),
			new ("Guinea", "GN"),
			new ("Guinea-Bissau", "GW"),
			new ("Guyana", "GY"),
			new ("Haiti", "HT"),
			new ("Honduras", "HN"),
			new ("Hungary", "HU"),
			new ("Iceland", "IS"),
			new ("India", "IN"),
			new ("Indonesia", "ID"),
			new ("Iran", "IR"),
			new ("Iraq", "IQ"),
			new ("Ireland", "IE"),
			new ("Israel", "IL"),
			new ("Italy", "IT"),
			new ("Jamaica", "JM"),
			new ("Japan", "JP"),
			new ("Jordan", "JO"),
			new ("Kazakhstan", "KZ"),
			new ("Kenya", "KE"),
			new ("Kiribati", "KI"),
			new ("Kuwait", "KW"),
			new ("Kyrgyzstan", "KG"),
			new ("Laos", "LA"),
			new ("Latvia", "LV"),
			new ("Lebanon", "LB"),
			new ("Lesotho", "LS"),
			new ("Liberia", "LR"),
			new ("Libya", "LY"),
			new ("Liechtenstein", "LI"),
			new ("Lithuania", "LT"),
			new ("Luxembourg", "LU"),
			new ("Madagascar", "MG"),
			new ("Malawi", "MW"),
			new ("Malaysia", "MY"),
			new ("Maldives", "MV"),
			new ("Mali", "ML"),
			new ("Malta", "MT"),
			new ("Marshall Islands", "MH"),
			new ("Mauritania", "MR"),
			new ("Mauritius", "MU"),
			new ("Mexico", "MX"),
			new ("Micronesia", "FM"),
			new ("Moldova", "MD"),
			new ("Monaco", "MC"),
			new ("Mongolia", "MN"),
			new ("Montenegro", "ME"),
			new ("Morocco", "MA"),
			new ("Mozambique", "MZ"),
			new ("Myanmar (formerly Burma)", "MM"),
			new ("Namibia", "NA"),
			new ("Nauru", "NR"),
			new ("Nepal", "NP"),
			new ("Netherlands", "NL"),
			new ("New Zealand", "NZ"),
			new ("Nicaragua", "NI"),
			new ("Niger", "NE"),
			new ("Nigeria", "NG"),
			new ("North Korea", "KP"),
			new ("North Macedonia (formerly Macedonia)", "MK"),
			new ("Norway", "NO"),
			new ("Oman","OM"),
			new ("Pakistan","PK"),
			new ("Palau","PW"),
			new ("Panama","PA"),
			new ("Papua New Guinea","PG"),
			new ("Paraguay","PY"),
			new ("Peru","PE"),
			new ("Philippines","PH"),
			new ("Poland","PL"),
			new ("Portugal","PT"),
			new ("Qatar","QA"),
			new ("Romania","RO"),
			new ("Russia","RU"),
			new ("Rwanda","RW"),
			new ("Saint Kitts and Nevis","KN"),
			new ("Saint Lucia","LC"),
			new ("Saint Vincent and the Grenadines","VC"),
			new ("Samoa","WS"),
			new ("San Marino","SM"),
			new ("Sao Tome and Principe","ST"),
			new ("Saudi Arabia","SA"),
			new ("Senegal","SN"),
			new ("Serbia","RS"),
			new ("Seychelles","SC"),
			new ("Sierra Leone","SL"),
			new ("Singapore","SG"),
			new ("Slovakia","SK"),
			new ("Slovenia","SI"),
			new ("Solomon Islands","SB"),
			new ("Somalia","SO"),
			new ("South Africa","ZA"),
			new ("South Korea","KR"),
			new ("South Sudan","SS"),
			new ("Spain","ES"),
			new ("Sri Lanka","LK"),
			new ("Sudan","SD"),
			new ("Suriname","SR"),
			new ("Sweden","SE"),
			new ("Switzerland","CH"),
			new ("Syria","SY"),
			new ("Tajikistan","TJ"),
			new ("Tanzania","TZ"),
			new ("Thailand","TH"),
			new ("Timor-Leste","TL"),
			new ("Togo","TG"),
			new ("Tonga","TO"),
			new ("Trinidad and Tobago","TT"),
			new ("Tunisia","TN"),
			new ("Turkey","TR"),
			new ("Turkmenistan","TM"),
			new ("Tuvalu","TV"),
			new ("Uganda","UG"),
			new ("Ukraine","UA"),
			new ("United Arab Emirates","AE"),
			new ("United Kingdom","GB"),
			new ("United States of America","US"),
			new ("Uruguay","UY"),
			new ("Uzbekistan","UZ"),
			new ("Vanuatu","VU"),
			new ("Venezuela","VE"),
			new ("Vietnam","VN"),
			new ("Yemen","YE"),
			new ("Zambia","ZM"),
			new ("Zimbabwe","ZW")
		};
	}
}
