on:
  push:
    paths-ignore:
      - '.github/**'
      - 'README.md'
      - '.editorconfig'
      - '.gitattributes'
      - '.gitignore'
      - 'LICENSE.txt'
      - 'docs/**'
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test-build:
    name: BUILD
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5
      - name: Build
        uses: EasyDesk/action-dotnet-build@v1.0.0
      - name: Upload NB Client for Windows
        uses: actions/upload-artifact@v4.3.3
        with:
          name: NBClientWindows
          path: ./UniversalClient/bin/Release/net8.0/
      - name: Upload NB Installer for Windows
        uses: actions/upload-artifact@v4.3.3
        with:
          name: NBInstallerWindows
          path: ./UniversalInstaller/bin/Release/net8.0/
