on:
  push:
    branches:
      - master
jobs:
  test-build:
    name: test if netblox even builds
    runs-on: windows-latest
    steps:
      - uses: EasyDesk/action-dotnet-build@v1.0.0
      - name: build
